name: Finder
version: 1.0
api-version: 1.15
author: Craig McDaniel
website: https://github.com/cpmcdaniel/bukkit-finder
main: org.kowboy.bukkit.finder.FinderPlugin

commands:
  find-entities:
    description: Finds living enties and displays summary information (number and closest coordinates for each type).
    aliases: [fes findes]
    usage: /find-entities
    permission: finder.find-entities
    permission-message: You don't have permission finder.find-entities
  find-entity:
    description: Finds living entities of the specified type. Displays location of the N closest matches.
    aliases: [fe finde]
    usage: /find-entity <entity_type>
    permission: finder.find-entity
    permission-message: You don't have permission finder.find-entity
  find-blocks:
    description: Finds blocks in proximity to the user of the types specified in the block-whitelist config.
    aliases: [fbs find-bs]
    usage: /find-blocks
    permission: finder.find-blocks
    permission-message: You don't have permission finder.find-blocks
  find-block:
    description: Finds blocks of the given block type in proximity to the user.
    aliases: [fb findb]
    usage: /find-block <block_type>
    permission: finder.find-block
    permission-message: You don't have permission finder.find-block


permissions:
  finder.*:
    # Permissions are not yet implemented.
    description: Allows execution of all finder commands.
    default: op

